name: stripe_example
description: Demonstrates how to use the Supabase functions to complete Stripe checkout
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^2.4.0
  supabase_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
